

style: |
  body {
    text-align: center;
  }

  
title: CHIDIMMA PRISCA OGU
description: Data scientists making sense of the world, one data set at a time
theme: jekyll-theme-minimal
show_downloads: true
